enableGlobalCache: true

packageExtensions:
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      '@types/webpack': '*'
      '@types/tapable': '*'
  purgecss-webpack-plugin@*:
    dependencies:
      '@types/webpack': '*'
  html-webpack-plugin@*:
    dependencies:
      '@types/webpack': '*'
      '@types/tapable': '*'
      '@types/html-minifier-terser': '*'
  webpack-chain@*:
    dependencies:
      '@types/webpack': '*'
      '@types/tapable': '*'
  apollo-link-error@*:
    dependencies:
      graphql: '*'
  graphql-yoga@*:
    dependencies:
      apollo-server-core: '*'
      aws-lambda: ^0.1.2
  karma-mocha@*:
    dependencies:
      mocha: '*'
  prisma-cli-engine@*:
    dependencies:
      graphql-config: '*'
  vue-apollo@*:
    dependencies:
      apollo-client: '*'
      apollo-link: '*'
      apollo-link-http-common: '*'
      graphql: '*'
  vuex-class@*:
    dependencies:
      vuex: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-sources.js
