packageExtensions:
  apollo-link-error@*:
    dependencies:
      graphql: "*"
  karma-mocha@*:
    dependencies:
      mocha: "*"
  prisma-cli-engine@*:
    dependencies:
      graphql-config: "*"
  graphql-yoga@*:
    dependencies:
      apollo-server-core: "*"
  vue-apollo@*:
    dependencies:
      apollo-client: "*"
      apollo-link: "*"
      apollo-link-http-common: "*"
      graphql: "*"
  vuex-class@*:
    dependencies:
      vuex: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.0.0-rc.30.js
