<div
    :class="[cPrefix]"
    :style="scrollerStyle"
    @mousemove.prevent="scrollerMouseMove($event)"
    @mouseup.prevent="scrollerMouseUp($event)"
    @wheel="mouseWheel($event)">
  <div
      :style="boxStyle"
      ref="box"
      v-xclass="xclass('box')">
    <slot></slot>
  </div>
  <div
      :style="barStyle"
      @click.stop.prevent
      @mousedown="barMouseDown($event)"
      ref="bar"
      v-show="barDisplay"
      v-xclass="xclass('bar')"></div>
</div>